import type { Product } from '../src/types';

export const PRODUCTS: Product[] = [
  {
    id: 'retatrutide-40mg',
    slug: 'retatrutide-40mg',
    name_pl: 'Retatrutide 40mg',
    name_en: 'Retatrutide 40mg',
    short_pl: 'Triple agonist GLP-1/GIP/Glucagon. Pen (wstrzykiwacz).',
    short_en: 'Triple agonist GLP-1/GIP/Glucagon. Pre-filled pen.',
    description_pl: 'Retatrutide to potrójny agonista receptorów GLP-1, GIP i glukagonu (tzw. "GLP-3"), opracowany przez Eli Lilly. Obecnie w fazie 3 badań klinicznych. Jeden z najbardziej obiecujących peptydów badawczych w dziedzinie metabolizmu.',
    description_en: 'Retatrutide is a triple agonist targeting GLP-1, GIP, and glucagon receptors (so-called "GLP-3"), developed by Eli Lilly. Currently in phase 3 clinical trials. One of the most promising research peptides in metabolic science.',
    image: '/images/products/retatrutide-40mg.jpg',
    coa: '/coa/retatrutide-coa.pdf',
    price_pln: 120000,
    price_gbp: 20000,
    stock_pl: 10,
    stock_uk: 10,
    category: 'weight-loss',
    format: 'pen',
    dosage: '40mg',
    disclaimer: true,
    featured: true,
    order: 1,
    protocol: {
      reconstitution: 'Pre-filled pen — no reconstitution needed',
      concentration: '40mg per pen',
      typicalDose: '0.5–2.0 mg weekly (titrated)',
      timing: 'AM or PM',
      frequency: '1x weekly',
      cycleLength: '8–48 weeks',
      stackNotes: 'Triple agonist (GLP-1/GIP/Glucagon). Titrate slowly: start low, increase over weeks.',
      storage: '-20°C lyophilized; 2-8°C after reconstitution, use within 30 days',
    },
  },
  {
    id: 'retatrutide-20mg',
    slug: 'retatrutide-20mg',
    name_pl: 'Retatrutide 20mg',
    name_en: 'Retatrutide 20mg',
    short_pl: 'Triple agonist GLP-1/GIP/Glucagon. Pen (wstrzykiwacz).',
    short_en: 'Triple agonist GLP-1/GIP/Glucagon. Pre-filled pen.',
    description_pl: 'Retatrutide to potrójny agonista receptorów GLP-1, GIP i glukagonu. Format pen 20mg — niższa dawka do protokołów badawczych.',
    description_en: 'Retatrutide is a triple agonist targeting GLP-1, GIP, and glucagon receptors. 20mg pen format — lower dose for research protocols.',
    image: '/images/products/retatrutide-20mg.jpg',
    coa: '/coa/retatrutide-coa.pdf',
    price_pln: 70000,
    price_gbp: 12000,
    stock_pl: 15,
    stock_uk: 10,
    category: 'weight-loss',
    format: 'pen',
    dosage: '20mg',
    disclaimer: true,
    featured: true,
    order: 2,
  },
  {
    id: 'bpc-157-5mg',
    slug: 'bpc-157-5mg',
    name_pl: 'BPC-157 5mg',
    name_en: 'BPC-157 5mg',
    short_pl: 'Pentadekapeptyd regeneracyjny. Szerokie spektrum działania.',
    short_en: 'Regenerative pentadecapeptide. Broad-spectrum healing.',
    description_pl: 'BPC-157 (Body Protection Compound) to syntetyczny peptyd 15-aminokwasowy pochodzący z białka ludzkiego soku żołądkowego. Jeden z najlepiej przebadanych peptydów regeneracyjnych w nauce przedklinicznej.',
    description_en: 'BPC-157 (Body Protection Compound) is a synthetic 15-amino acid peptide derived from a protein found in human gastric juice. One of the most researched healing peptides in preclinical science.',
    image: '/images/products/bpc-157-5mg.jpg',
    price_pln: 10000,
    price_gbp: 2000,
    stock_pl: 50,
    stock_uk: 30,
    category: 'healing',
    format: 'vial',
    dosage: '5mg',
    disclaimer: true,
    featured: true,
    order: 3,
  },
  {
    id: 'bpc-157-10mg',
    slug: 'bpc-157-10mg',
    name_pl: 'BPC-157 10mg',
    name_en: 'BPC-157 10mg',
    short_pl: 'Pentadekapeptyd regeneracyjny. Większa dawka badawcza.',
    short_en: 'Regenerative pentadecapeptide. Higher research dose.',
    description_pl: 'BPC-157 10mg — większa fiolka pentadekapeptyd regeneracyjnego pochodzącego z białka ludzkiego soku żołądkowego. Aktywuje receptor VEGFR2 (angiogeneza), kompleksy FAK-paksylina (migracja komórek) oraz szlak JAK-2 (przeżywalność komórek). Badany w kontekście gojenia ścięgien, więzadeł, mięśni, ochrony błony śluzowej przewodu pokarmowego oraz neuroprotekcji. Format 10mg dedykowany do rozszerzonych protokołów badawczych wymagających większej ilości substancji.',
    description_en: 'BPC-157 10mg — larger vial of the regenerative pentadecapeptide derived from human gastric juice protein. Activates VEGFR2 receptor (angiogenesis), FAK-paxillin complexes (cell migration), and JAK-2 signaling (cell survival). Studied for tendon, ligament, muscle healing, GI tract mucosal protection, and neuroprotection. 10mg format dedicated to extended research protocols requiring larger quantities.',
    image: '/images/products/bpc-157-10mg.jpg',
    price_pln: 15000,
    price_gbp: 3000,
    stock_pl: 40,
    stock_uk: 25,
    category: 'healing',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 4,
  },
  {
    id: 'tb-500-5mg',
    slug: 'tb-500-5mg',
    name_pl: 'TB-500 5mg',
    name_en: 'TB-500 5mg',
    short_pl: 'Analog Tymozyny Beta-4. Mobilizacja komórek macierzystych.',
    short_en: 'Thymosin Beta-4 analog. Stem cell mobilization.',
    description_pl: 'TB-500 to syntetyczny analog naturalnie występującej Tymozyny Beta-4, białka uwalnianego przez płytki krwi i makrofagi po urazie. Opisywany jako "jedna z najbardziej aktywnych molekuł gojenia ran".',
    description_en: 'TB-500 is a synthetic analog of naturally occurring Thymosin Beta-4, a protein released by platelets and macrophages after injury. Described as "one of the most active wound-healing molecules" in literature.',
    image: '/images/products/tb-500-5mg.jpg',
    price_pln: 11000,
    price_gbp: 2200,
    stock_pl: 35,
    stock_uk: 20,
    category: 'healing',
    format: 'vial',
    dosage: '5mg',
    disclaimer: true,
    featured: false,
    order: 5,
  },
  {
    id: 'nad-100mg',
    slug: 'nad-100mg',
    name_pl: 'NAD+ 100mg',
    name_en: 'NAD+ 100mg',
    short_pl: 'Koenzym kluczowy dla 500+ reakcji enzymatycznych.',
    short_en: 'Coenzyme central to 500+ enzymatic reactions.',
    description_pl: 'NAD+ (Dinukleotyd nikotynamidoadeninowy) — koenzym obecny w każdej żywej komórce, centralny dla ponad 500 reakcji enzymatycznych. Kluczowy ko-substrat dla sirtuiny (SIRT1-7) regulujących ekspresję genów i naprawę DNA, oraz PARP odpowiedzialnych za naprawę uszkodzeń DNA. Poziom NAD+ spada drastycznie z wiekiem — badania łączą ten spadek ze starzeniem się komórkowym, dysfunkcją mitochondrialną i chorobami neurodegeneracyjnymi. Format 100mg do protokołów badawczych o standardowym zakresie.',
    description_en: 'NAD+ (Nicotinamide Adenine Dinucleotide) — a coenzyme found in every living cell, central to over 500 enzymatic reactions. Essential co-substrate for sirtuins (SIRT1-7) regulating gene expression and DNA repair, and PARPs responsible for DNA damage repair. NAD+ levels decline sharply with age — research links this decline to cellular aging, mitochondrial dysfunction, and neurodegenerative diseases. 100mg format for standard-range research protocols.',
    image: '/images/products/nad-100mg.jpg',
    price_pln: 15000,
    price_gbp: 3000,
    stock_pl: 30,
    stock_uk: 20,
    category: 'anti-aging',
    format: 'vial',
    dosage: '100mg',
    disclaimer: true,
    featured: false,
    order: 6,
  },
  {
    id: 'nad-500mg',
    slug: 'nad-500mg',
    name_pl: 'NAD+ 500mg',
    name_en: 'NAD+ 500mg',
    short_pl: 'Koenzym anti-aging. Większa dawka badawcza.',
    short_en: 'Anti-aging coenzyme. Higher research dose.',
    description_pl: 'NAD+ 500mg — duża fiolka do rozszerzonych protokołów badawczych nad starzeniem komórkowym, metabolizmem energetycznym i naprawą DNA. Kluczowy ko-substrat dla sirtuiny i PARP, centralny dla fosforylacji oksydacyjnej w mitochondriach (produkcja ATP). Badania z 2026 roku łączą NAD+ z potencjałem w modelach choroby Alzheimera i Parkinsona. Format 500mg dedykowany do wielotygodniowych protokołów wymagających większych ilości.',
    description_en: 'NAD+ 500mg — large vial for extended research protocols on cellular aging, energy metabolism, and DNA repair. Essential co-substrate for sirtuins and PARPs, central to mitochondrial oxidative phosphorylation (ATP production). 2026 research links NAD+ to potential in Alzheimer\'s and Parkinson\'s disease models. 500mg format dedicated to multi-week protocols requiring larger quantities.',
    image: '/images/products/nad-500mg.jpg',
    price_pln: 22500,
    price_gbp: 4500,
    stock_pl: 15,
    stock_uk: 10,
    category: 'anti-aging',
    format: 'vial',
    dosage: '500mg',
    disclaimer: true,
    featured: true,
    order: 7,
  },
  {
    id: 'ghk-cu-50mg',
    slug: 'ghk-cu-50mg',
    name_pl: 'GHK-Cu 50mg',
    name_en: 'GHK-Cu 50mg',
    short_pl: 'Peptyd miedziowy. Modulacja 4000+ genów.',
    short_en: 'Copper peptide. 4,000+ gene modulation.',
    description_pl: 'GHK-Cu (Glycyl-L-histydyl-L-lizyna z miedzią) — naturalnie występujący tripeptyd ludzki, odkryty w 1973. Moduluje ekspresję ponad 4000 genów, wiele z nich związanych z naprawą DNA i obroną antyoksydacyjną.',
    description_en: 'GHK-Cu (Glycyl-L-histidyl-L-lysine Copper) — a naturally occurring human tripeptide discovered in 1973. Modulates expression of over 4,000 genes, many involved in DNA repair and antioxidant defense.',
    image: '/images/products/ghk-cu-50mg.jpg',
    price_pln: 11000,
    price_gbp: 2200,
    stock_pl: 25,
    stock_uk: 15,
    category: 'anti-aging',
    format: 'vial',
    dosage: '50mg',
    disclaimer: true,
    featured: false,
    order: 8,
  },
  {
    id: 'ghk-cu-100mg',
    slug: 'ghk-cu-100mg',
    name_pl: 'GHK-Cu 100mg',
    name_en: 'GHK-Cu 100mg',
    short_pl: 'Peptyd miedziowy. Większa dawka badawcza.',
    short_en: 'Copper peptide. Higher research dose.',
    description_pl: 'GHK-Cu 100mg — większa fiolka peptydu miedziowego modulującego ekspresję ponad 4000 ludzkich genów. Stymuluje syntezę kolagenu, elastyny i glikozaminoglikanów. Badania wykazały 31.6% redukcję objętości zmarszczek w 8-tygodniowym badaniu topikalnym. Stosowany w badaniach nad regeneracją skóry, stymulacją mieszków włosowych, remodelowaniem blizn i systemowym gojeniem tkanek. Format 100mg do rozszerzonych protokołów badawczych.',
    description_en: 'GHK-Cu 100mg — larger vial of the copper peptide modulating expression of over 4,000 human genes. Stimulates synthesis of collagen, elastin, and glycosaminoglycans. Studies showed 31.6% wrinkle volume reduction in 8-week topical trial. Used in research on skin regeneration, hair follicle stimulation, scar remodeling, and systemic tissue healing. 100mg format for extended research protocols.',
    image: '/images/products/ghk-cu-100mg.jpg',
    price_pln: 20000,
    price_gbp: 4000,
    stock_pl: 15,
    stock_uk: 10,
    category: 'anti-aging',
    format: 'vial',
    dosage: '100mg',
    disclaimer: true,
    featured: false,
    order: 9,
  },
  {
    id: 'mots-c-10mg',
    slug: 'mots-c-10mg',
    name_pl: 'MOTS-c 10mg',
    name_en: 'MOTS-c 10mg',
    short_pl: 'Peptyd mitochondrialny. Regulator metabolizmu.',
    short_en: 'Mitochondrial peptide. Metabolic regulator.',
    description_pl: 'MOTS-c — unikalny peptyd kodowany przez mitochondrialne DNA (nie jądrowe). Działa przez szlak Folate-AICAR-AMPK jako systemowy regulator metabolizmu.',
    description_en: 'MOTS-c — a unique peptide encoded by mitochondrial DNA (not nuclear). Acts through the Folate-AICAR-AMPK pathway as a systemic metabolic regulator.',
    image: '/images/products/mots-c-10mg.jpg',
    coa: '/coa/mots-c-coa.pdf',
    price_pln: 12500,
    price_gbp: 2500,
    stock_pl: 20,
    stock_uk: 15,
    category: 'metabolic',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 10,
  },
  {
    id: 'ss-31-10mg',
    slug: 'ss-31-10mg',
    name_pl: 'SS-31 10mg',
    name_en: 'SS-31 10mg',
    short_pl: 'Elamipretide. Ochrona mitochondriów.',
    short_en: 'Elamipretide. Mitochondrial protection.',
    description_pl: 'SS-31 (Elamipretide) — syntetyczny tetrapeptyd selektywnie celujący w wewnętrzną błonę mitochondrialną. Stabilizuje kristy, redukuje stres oksydacyjny, zwiększa produkcję ATP.',
    description_en: 'SS-31 (Elamipretide) — a synthetic tetrapeptide that selectively targets the inner mitochondrial membrane. Stabilizes cristae, reduces oxidative stress, enhances ATP production.',
    image: '/images/products/ss-31-10mg.jpg',
    price_pln: 12500,
    price_gbp: 2500,
    stock_pl: 15,
    stock_uk: 10,
    category: 'mitochondrial',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 11,
  },
  {
    id: 'cjc-1295-5mg',
    slug: 'cjc-1295-no-dac-5mg',
    name_pl: 'CJC-1295 No DAC 5mg',
    name_en: 'CJC-1295 No DAC 5mg',
    short_pl: 'Analog GHRH. Pulsacyjne uwalnianie hormonu wzrostu.',
    short_en: 'GHRH analog. Pulsatile growth hormone release.',
    description_pl: 'CJC-1295 No DAC (Mod-GRF 1-29) — zmodyfikowany analog hormonu uwalniającego hormon wzrostu. Stymuluje naturalne pulsacyjne wydzielanie GH bez zaburzania fizjologicznego rytmu.',
    description_en: 'CJC-1295 No DAC (Mod-GRF 1-29) — a modified analog of Growth Hormone-Releasing Hormone. Stimulates natural pulsatile GH secretion without disrupting physiological rhythm.',
    image: '/images/products/cjc-1295-5mg.jpg',
    price_pln: 10000,
    price_gbp: 2000,
    stock_pl: 40,
    stock_uk: 25,
    category: 'growth-hormone',
    format: 'vial',
    dosage: '5mg',
    disclaimer: true,
    featured: false,
    order: 12,
  },
  {
    id: 'cjc-1295-10mg',
    slug: 'cjc-1295-no-dac-10mg',
    name_pl: 'CJC-1295 No DAC 10mg',
    name_en: 'CJC-1295 No DAC 10mg',
    short_pl: 'Analog GHRH. Większa dawka do rozszerzonych protokołów.',
    short_en: 'GHRH analog. Higher dose for extended protocols.',
    description_pl: 'CJC-1295 No DAC 10mg (Mod-GRF 1-29) — większa fiolka zmodyfikowanego analogu hormonu uwalniającego hormon wzrostu. Stymuluje pulsacyjne wydzielanie GH poprzez receptor GHRH, zachowując fizjologiczny rytm pulsacji. Brak grupy DAC skraca okres półtrwania do około 30 minut, co pozwala kontrolować czas działania. Najczęściej badany w synergii z Ipamorelin dla wzmocnionego pulsu GH. Format 10mg dedykowany do wielotygodniowych protokołów badawczych.',
    description_en: 'CJC-1295 No DAC 10mg (Mod-GRF 1-29) — larger vial of the modified Growth Hormone-Releasing Hormone analog. Stimulates pulsatile GH secretion via GHRH receptor while preserving physiological pulse rhythm. Absence of DAC group shortens half-life to approximately 30 minutes, allowing controlled duration of action. Most commonly studied in synergy with Ipamorelin for enhanced GH pulse. 10mg format dedicated to extended multi-week research protocols.',
    image: '/images/products/cjc-1295-5mg.jpg',
    price_pln: 15000,
    price_gbp: 3000,
    stock_pl: 25,
    stock_uk: 15,
    category: 'growth-hormone',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 28,
  },
  {
    id: 'melanotan-2-10mg',
    slug: 'melanotan-2-10mg',
    name_pl: 'Melanotan 2 10mg',
    name_en: 'Melanotan 2 10mg',
    short_pl: 'Analog α-MSH. Stymulacja melanogenezy.',
    short_en: 'α-MSH analog. Melanogenesis stimulation.',
    description_pl: 'Melanotan II — syntetyczny cykliczny analog alfa-melanocytostymulującego hormonu (α-MSH). Agonista receptorów melanokortynowych MC1, MC3, MC4, MC5.',
    description_en: 'Melanotan II — a synthetic cyclic analog of alpha-melanocyte-stimulating hormone (α-MSH). Agonist at melanocortin receptors MC1, MC3, MC4, MC5.',
    image: '/images/products/melanotan-2-10mg.jpg',
    price_pln: 12500,
    price_gbp: 2500,
    stock_pl: 35,
    stock_uk: 25,
    category: 'melanogenesis',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 13,
  },
  {
    id: '5-amino-1mq-10mg',
    slug: '5-amino-1mq-10mg',
    name_pl: '5-Amino-1MQ 10mg',
    name_en: '5-Amino-1MQ 10mg',
    short_pl: 'Inhibitor NNMT. Zwiększa poziom NAD+.',
    short_en: 'NNMT inhibitor. Increases NAD+ levels.',
    description_pl: '5-Amino-1MQ — mała molekuła hamująca enzym NNMT (N-metylotransferaza nikotynamidu), wysoko ekspresjonowany w tkance tłuszczowej. Zwiększa poziom NAD+ 1,2-1,6x w komórkach.',
    description_en: '5-Amino-1MQ — a small molecule that inhibits the enzyme NNMT (Nicotinamide N-Methyltransferase), highly expressed in adipose tissue. Increases NAD+ levels 1.2–1.6x in cells.',
    image: '/images/products/5-amino-1mq-10mg.jpg',
    price_pln: 15500,
    price_gbp: 3100,
    stock_pl: 20,
    stock_uk: 15,
    category: 'metabolic',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 14,
  },
  {
    id: 'ipamorelin-5mg',
    slug: 'ipamorelin-5mg',
    name_pl: 'Ipamorelin 5mg',
    name_en: 'Ipamorelin 5mg',
    short_pl: 'Najbardziej selektywny GHRP. Czysty profil GH.',
    short_en: 'Most selective GHRP. Clean GH profile.',
    description_pl: 'Ipamorelin — syntetyczny pentapeptyd, uznawany za najbardziej selektywny peptyd uwalniający hormon wzrostu (GHRP). Nie wpływa na ACTH-kortyzol ani prolaktynę.',
    description_en: 'Ipamorelin — a synthetic pentapeptide considered the most selective Growth Hormone Releasing Peptide (GHRP). Does not affect ACTH-cortisol or prolactin.',
    image: '/images/products/ipamorelin-5mg.jpg',
    price_pln: 10000,
    price_gbp: 2000,
    stock_pl: 40,
    stock_uk: 25,
    category: 'growth-hormone',
    format: 'vial',
    dosage: '5mg',
    disclaimer: true,
    featured: false,
    order: 15,
  },
  {
    id: 'ipamorelin-10mg',
    slug: 'ipamorelin-10mg',
    name_pl: 'Ipamorelin 10mg',
    name_en: 'Ipamorelin 10mg',
    short_pl: 'Najbardziej selektywny GHRP. Większa dawka.',
    short_en: 'Most selective GHRP. Higher dose.',
    description_pl: 'Ipamorelin 10mg — większa fiolka najbardziej selektywnego peptydu uwalniającego hormon wzrostu (GHRP). W przeciwieństwie do GHRP-6 i GHRP-2 nie aktywuje osi ACTH-kortyzol, nie stymuluje znacząco prolaktyny ani apetytu. Wywołuje pulsacyjne uwalnianie GH poprzez receptor ghreliny/GHSR-1a. Najczęściej badany w połączeniu z CJC-1295 No DAC dla synergistycznego efektu. Format 10mg do rozszerzonych wielotygodniowych protokołów.',
    description_en: 'Ipamorelin 10mg — larger vial of the most selective Growth Hormone Releasing Peptide (GHRP). Unlike GHRP-6 and GHRP-2, does not activate the ACTH-cortisol axis, does not significantly stimulate prolactin or appetite. Triggers pulsatile GH release via the ghrelin/GHSR-1a receptor. Most commonly studied in combination with CJC-1295 No DAC for synergistic effect. 10mg format for extended multi-week protocols.',
    image: '/images/products/ipamorelin-10mg.jpg',
    price_pln: 15000,
    price_gbp: 3000,
    stock_pl: 30,
    stock_uk: 20,
    category: 'growth-hormone',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 16,
  },
  {
    id: 'selank-5mg',
    slug: 'selank-5mg',
    name_pl: 'Selank 5mg',
    name_en: 'Selank 5mg',
    short_pl: 'Neuropeptyd anksjolityczny. Bez tolerancji i uzależnienia.',
    short_en: 'Anxiolytic neuropeptide. No tolerance or dependence.',
    description_pl: 'Selank — syntetyczny heptapeptyd opracowany przez Rosyjską Akademię Nauk, pochodna tuftyny. Moduluje neurotransmisję GABAergiczną z efektem anksjolitycznym porównywalnym z benzodiazepinami — bez tolerancji i uzależnienia.',
    description_en: 'Selank — a synthetic heptapeptide developed at the Russian Academy of Sciences, derived from tuftsin. Modulates GABAergic neurotransmission with anxiolytic effects comparable to benzodiazepines — without tolerance or dependence.',
    image: '/images/products/selank-5mg.jpg',
    price_pln: 9000,
    price_gbp: 1800,
    stock_pl: 25,
    stock_uk: 15,
    category: 'cognitive',
    format: 'vial',
    dosage: '5mg',
    disclaimer: true,
    featured: false,
    order: 17,
  },
  {
    id: 'selank-10mg',
    slug: 'selank-10mg',
    name_pl: 'Selank 10mg',
    name_en: 'Selank 10mg',
    short_pl: 'Neuropeptyd anksjolityczny. Większa dawka.',
    short_en: 'Anxiolytic neuropeptide. Higher dose.',
    description_pl: 'Selank 10mg — większa fiolka neuropeptydu anksjolitycznego opracowanego przez Rosyjską Akademię Nauk. Moduluje neurotransmisję GABAergiczną z efektem porównywalnym z benzodiazepinami — bez tolerancji, uzależnienia i sedacji. Wpływa na poziomy noradrenaliny, serotoniny i dopaminy. Zarejestrowany jako lek w Rosji na leczenie zaburzeń lękowych uogólnionych. Format 10mg do rozszerzonych protokołów badawczych, podawanie donosowe lub podskórne.',
    description_en: 'Selank 10mg — larger vial of the anxiolytic neuropeptide developed at the Russian Academy of Sciences. Modulates GABAergic neurotransmission with effects comparable to benzodiazepines — without tolerance, dependence, or sedation. Influences noradrenaline, serotonin, and dopamine levels. Registered as a drug in Russia for generalized anxiety disorder. 10mg format for extended research protocols, intranasal or subcutaneous administration.',
    image: '/images/products/selank-10mg.jpg',
    price_pln: 17900,
    price_gbp: 3699,
    stock_pl: 20,
    stock_uk: 10,
    category: 'cognitive',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 18,
  },
  {
    id: 'snap-8-10mg',
    slug: 'snap-8-10mg',
    name_pl: 'SNAP-8 10mg',
    name_en: 'SNAP-8 10mg',
    short_pl: 'Neuropeptyd anti-aging. Topikalna alternatywa botoksu.',
    short_en: 'Anti-aging neuropeptide. Topical Botox alternative.',
    description_pl: 'SNAP-8 (Acetyl Octapeptide-3) — zaawansowany 8-aminokwasowy neuropeptyd kosmeceutyczny. Częściowo hamuje kompleks SNARE, redukując skurcze mięśni mimicznych. Do 63% redukcji zmarszczek w 28-dniowym badaniu.',
    description_en: 'SNAP-8 (Acetyl Octapeptide-3) — an advanced 8-amino acid cosmeceutical neuropeptide. Partially inhibits the SNARE complex, reducing expression muscle contractions. Up to 63% wrinkle reduction in 28-day study.',
    image: '/images/products/snap-8-10mg.jpg',
    price_pln: 10000,
    price_gbp: 2000,
    stock_pl: 30,
    stock_uk: 20,
    category: 'cosmeceutical',
    format: 'vial',
    dosage: '10mg',
    disclaimer: true,
    featured: false,
    order: 19,
  },
  {
    id: 'klow-80mg',
    slug: 'klow-80mg',
    name_pl: 'KLOW 80mg',
    name_en: 'KLOW 80mg',
    short_pl: 'Blend regeneracyjny: BPC-157 + GHK-Cu + TB-500.',
    short_en: 'Regenerative blend: BPC-157 + GHK-Cu + TB-500.',
    description_pl: 'KLOW 80mg to autorski blend Peptivex Labs łączący trzy najlepiej udokumentowane peptydy regeneracyjne w jednej fiolce: BPC-157 (pentadekapeptyd z soku żołądkowego), GHK-Cu (peptyd miedziowy modulujący 4000+ genów) oraz TB-500 (analog Tymozyny Beta-4). Format dedykowany do rozszerzonych protokołów badawczych nad regeneracją tkanek, gojeniem ran i remodelingiem skóry.',
    description_en: 'KLOW 80mg is a proprietary Peptivex Labs blend combining three of the best-documented regenerative peptides in a single vial: BPC-157 (pentadecapeptide from gastric juice), GHK-Cu (copper peptide modulating 4000+ genes), and TB-500 (Thymosin Beta-4 analog). Format dedicated to extended research protocols on tissue regeneration, wound healing, and skin remodeling.',
    image: '/images/products/klow-80mg.jpg',
    coa: '/coa/klow-coa.pdf',
    price_pln: 40000,
    price_gbp: 8000,
    stock_pl: 20,
    stock_uk: 15,
    category: 'blend',
    format: 'vial',
    dosage: '80mg',
    disclaimer: true,
    featured: true,
    order: 20,
  },
  {
    id: 'glow-70mg',
    slug: 'glow-70mg',
    name_pl: 'GLOW 70mg',
    name_en: 'GLOW 70mg',
    short_pl: 'Blend regeneracyjny: BPC-157 + GHK-Cu.',
    short_en: 'Regenerative blend: BPC-157 + GHK-Cu.',
    description_pl: 'GLOW 70mg to blend Peptivex Labs łączący BPC-157 z GHK-Cu w jednej fiolce. Połączenie peptydu regeneracyjnego z peptydem miedziowym modulującym 4000+ genów skóry. Format do rozszerzonych protokołów badawczych nad regeneracją skóry, remodelingiem blizn i stymulacją syntezy kolagenu.',
    description_en: 'GLOW 70mg is a Peptivex Labs blend combining BPC-157 with GHK-Cu in a single vial. Pairs the regenerative pentadecapeptide with the copper peptide modulating 4000+ skin genes. Format for extended research protocols on skin regeneration, scar remodeling, and collagen synthesis stimulation.',
    image: '/images/products/glow-70mg.jpg',
    price_pln: 35000,
    price_gbp: 7000,
    stock_pl: 20,
    stock_uk: 15,
    category: 'blend',
    format: 'vial',
    dosage: '70mg',
    disclaimer: true,
    featured: true,
    order: 21,
  },
  {
    id: 'bac-water-10ml',
    slug: 'bac-water-10ml',
    name_pl: 'Bacteriostatic Water 10ml',
    name_en: 'Bacteriostatic Water 10ml',
    short_pl: 'Woda bakteriostatyczna do rekonstytucji peptydów.',
    short_en: 'Bacteriostatic water for peptide reconstitution.',
    description_pl: 'Woda bakteriostatyczna 10ml — sterylny rozpuszczalnik z 0.9% alkoholem benzylowym do rekonstytucji peptydów liofilizowanych. Konieczna do przygotowania roztworów badawczych z fiolek lyo. Pojemność 10ml pozwala rozpuścić wiele fiolek w trakcie protokołu.',
    description_en: 'Bacteriostatic water 10ml — sterile diluent with 0.9% benzyl alcohol for reconstituting lyophilized peptides. Required for preparing research solutions from lyo vials. 10ml capacity covers multiple vials during a protocol.',
    image: '/images/products/bac-water-10ml.jpg',
    price_pln: 2500,
    price_gbp: 500,
    stock_pl: 100,
    stock_uk: 80,
    category: 'accessory',
    format: 'vial',
    dosage: '10ml',
    disclaimer: true,
    featured: false,
    order: 22,
  },
  {
    id: 'retatrutide-set-60mg',
    slug: 'retatrutide-set-60mg',
    name_pl: 'Retatrutide SET 20mg + 40mg',
    name_en: 'Retatrutide SET 20mg + 40mg',
    short_pl: 'Zestaw dwóch penów Retatrutide (20mg i 40mg).',
    short_en: 'Set of two Retatrutide pens (20mg and 40mg).',
    description_pl: 'Retatrutide SET to zestaw dwóch penów Retatrutide w jednym opakowaniu: 20mg (niższa dawka do titracji) + 40mg (pełna dawka badawcza). Łącznie 60mg aktywnego peptydu w formacie pre-filled pen, bez konieczności rekonstytucji. Przeznaczone do rozszerzonych protokołów badawczych z pełnym schematem titracji.',
    description_en: 'Retatrutide SET bundles two Retatrutide pens in one package: 20mg (lower titration dose) + 40mg (full research dose). Total 60mg of active peptide in pre-filled pen format, no reconstitution needed. Designed for extended research protocols with full titration schedule.',
    image: '/images/products/retatrutide-set.jpg',
    coa: '/coa/retatrutide-coa.pdf',
    price_pln: 190000,
    price_gbp: 38000,
    stock_pl: 8,
    stock_uk: 8,
    category: 'combo',
    format: 'pen',
    dosage: '20mg + 40mg',
    disclaimer: true,
    featured: true,
    order: 23,
  },
  {
    id: 'combo-nad-motsc-bac',
    slug: 'combo-nad-motsc-bac',
    name_pl: 'Combo: NAD+ 500mg + MOTS-c 10mg + Bac Water',
    name_en: 'Combo: NAD+ 500mg + MOTS-c 10mg + Bac Water',
    short_pl: 'Zestaw metaboliczny. Mitochondria + długowieczność.',
    short_en: 'Metabolic stack. Mitochondria + longevity.',
    description_pl: 'Zestaw skupiony na funkcji mitochondrialnej i metabolizmie: NAD+ 500mg (koenzym dla 500+ reakcji, ko-substrat sirtuin), MOTS-c 10mg (peptyd kodowany przez mtDNA, regulator AMPK), plus Bac Water 10ml do rekonstytucji. Kompletny zestaw badawczy bez konieczności kupowania rozpuszczalnika oddzielnie.',
    description_en: 'Stack focused on mitochondrial function and metabolism: NAD+ 500mg (coenzyme for 500+ reactions, sirtuin co-substrate), MOTS-c 10mg (mtDNA-encoded peptide, AMPK regulator), plus Bac Water 10ml for reconstitution. Complete research bundle, no need to source diluent separately.',
    image: '/images/products/nad-500mg.jpg',
    price_pln: 37500,
    price_gbp: 6500,
    stock_pl: 12,
    stock_uk: 10,
    category: 'combo',
    format: 'vial',
    dosage: 'NAD+ 500mg + MOTS-c 10mg + Bac 10ml',
    disclaimer: true,
    featured: false,
    order: 24,
  },
  {
    id: 'combo-cjc-ipa-bac',
    slug: 'combo-cjc-ipa-bac',
    name_pl: 'Combo: CJC-1295 No DAC 10mg + Ipamorelin 10mg + Bac Water',
    name_en: 'Combo: CJC-1295 No DAC 10mg + Ipamorelin 10mg + Bac Water',
    short_pl: 'Klasyczny stack GH. Synergia GHRH + GHRP.',
    short_en: 'Classic GH stack. GHRH + GHRP synergy.',
    description_pl: 'Klasyczny zestaw badawczy nad hormonem wzrostu: CJC-1295 No DAC 10mg (analog GHRH) + Ipamorelin 10mg (najbardziej selektywny GHRP) + Bac Water 10ml. Dwa peptydy stosowane w literaturze naukowej jako synergiczna para do protokołów nad pulsacyjnym uwalnianiem GH. Format 10mg + 10mg dedykowany do rozszerzonych wielotygodniowych protokołów.',
    description_en: 'Classic growth hormone research stack: CJC-1295 No DAC 10mg (GHRH analog) + Ipamorelin 10mg (most selective GHRP) + Bac Water 10ml. Two peptides cited in scientific literature as a synergistic pair for pulsatile GH release protocols. 10mg + 10mg format dedicated to extended multi-week protocols.',
    image: '/images/products/combo-cjc-ipa-bac.jpg',
    price_pln: 30000,
    price_gbp: 6000,
    stock_pl: 20,
    stock_uk: 15,
    category: 'combo',
    format: 'vial',
    dosage: 'CJC 10mg + Ipa 10mg + Bac 10ml',
    disclaimer: true,
    featured: false,
    order: 25,
  },
  {
    id: 'combo-bpc-tb-bac',
    slug: 'combo-bpc-tb-bac',
    name_pl: 'Combo: BPC-157 10mg + TB-500 5mg + Bac Water',
    name_en: 'Combo: BPC-157 10mg + TB-500 5mg + Bac Water',
    short_pl: 'Stack regeneracyjny. Gojenie + mobilizacja komórek.',
    short_en: 'Regenerative stack. Healing + cell mobilization.',
    description_pl: 'Zestaw regeneracyjny łączący BPC-157 10mg (pentadekapeptyd, angiogeneza + migracja komórkowa) z TB-500 5mg (analog Tymozyny Beta-4, mobilizacja komórek macierzystych). Dwa najczęściej stackowane peptydy regeneracyjne w literaturze, plus Bac Water 10ml do rekonstytucji.',
    description_en: 'Regenerative stack combining BPC-157 10mg (pentadecapeptide, angiogenesis + cell migration) with TB-500 5mg (Thymosin Beta-4 analog, stem cell mobilization). The two most commonly stacked regenerative peptides in literature, plus Bac Water 10ml for reconstitution.',
    image: '/images/products/combo-bpc-tb-bac.jpg',
    price_pln: 22500,
    price_gbp: 4500,
    stock_pl: 20,
    stock_uk: 15,
    category: 'combo',
    format: 'vial',
    dosage: 'BPC 10mg + TB 5mg + Bac 10ml',
    disclaimer: true,
    featured: false,
    order: 26,
  },
  {
    id: 'combo-reta-motsc-bac',
    slug: 'combo-reta-motsc-bac',
    name_pl: 'Combo: Retatrutide 40mg + MOTS-c 10mg + Bac Water',
    name_en: 'Combo: Retatrutide 40mg + MOTS-c 10mg + Bac Water',
    short_pl: 'Premium stack metaboliczny. Triple agonist + mitochondria.',
    short_en: 'Premium metabolic stack. Triple agonist + mitochondria.',
    description_pl: 'Premium zestaw metaboliczny łączący Retatrutide 40mg pen (triple agonist GLP-1/GIP/Glucagon) z MOTS-c 10mg (peptyd mitochondrialny) oraz Bac Water 10ml. Kompletny protokół badawczy obejmujący oś regulacji glukozy oraz funkcję mitochondrialną. Dostępna opcja injection pen dla MOTS-c 10mg.',
    description_en: 'Premium metabolic stack combining Retatrutide 40mg pen (GLP-1/GIP/Glucagon triple agonist) with MOTS-c 10mg (mitochondrial peptide) and Bac Water 10ml. Complete research protocol covering the glucose regulation axis and mitochondrial function. Optional injection pen available for MOTS-c 10mg.',
    image: '/images/products/combo-reta-motsc-bac.jpg',
    coa: '/coa/retatrutide-coa.pdf',
    price_pln: 105000,
    price_gbp: 21000,
    stock_pl: 8,
    stock_uk: 8,
    category: 'combo',
    format: 'pen',
    dosage: 'Reta 40mg + MOTS-c 10mg + Bac 10ml',
    disclaimer: true,
    featured: false,
    order: 27,
  },
];
